In [21]:
import pandas as pd
import pylab as plt
import numpy as np

In [22]:
df = pd.read_csv("G:\Data science\Capstone_insurance\Purchase.csv")

In [23]:
import xgboost

In [24]:
print(df)

        QuoteNumber Original_Quote_Date  QuoteConversion_Flag Field6  Field7  \
0                 1          2013-08-16                     0      B      23
1                 2          2014-04-22                     0      F       7
2                 4          2014-08-25                     0      F       7
3                 6          2013-04-15                     0      J      10
4                 8          2014-01-25                     0      E      23
5                12          2014-01-18                     0      E      14
6                13          2013-11-01                     0      J      23
7                14          2014-05-14                     0      B      25
8                18          2013-06-19                     0      J      10
9                19          2013-06-18                     0      F      11
10               20          2013-09-24                     0      B      23
11               22          2013-06-11                     0      B      23
12               25          2013-10-22                     1      J      20
13               26          2013-08-20                     1      B      24
14               28          2015-02-24                     0      F      22
15               29          2014-10-27                     0      J      26
16               30          2015-02-06                     0      B      25
17               32          2013-10-02                     1      F      11
18               35          2014-09-15                     0      B      25
19               37          2013-06-18                     0      E      23
20               38          2014-03-18                     0      J      26
21               40          2014-10-15                     0      J      23
22               41          2014-04-03                     0      F       7
23               44          2015-03-31                     0      F      22
24               45          2013-05-30                     0      B      19
25               47          2015-03-30                     1      F      22
26               50          2013-09-17                     0      B      24
27               51          2015-03-07                     0      C      17
28               53          2013-06-06                     0      J      23
29               57          2013-01-22                     0      B       6
...             ...                 ...                   ...    ...     ...
260723       434549          2015-01-07                     0      K      21
260724       434550          2015-04-11                     0      K      21
260725       434551          2014-01-20                     0      B      23
260726       434552          2014-05-14                     0      J      23
260727       434555          2015-03-31                     0      B      23
260728       434556          2013-10-02                     0      B      23
260729       434557          2015-02-18                     0      C      17
260730       434559          2013-11-09                     0      F      11
260731       434561          2014-07-20                     0      J      23
260732       434562          2015-04-01                     0      F      23
260733       434564          2014-02-04                     1      B      25
260734       434566          2014-01-21                     0      J      23
260735       434567          2013-04-21                     0      F      23
260736       434568          2013-07-01                     0      B      24
260737       434569          2014-03-10                     0      E      23
260738       434571          2014-04-11                     0      E      23
260739       434572          2014-01-24                     0      B      25
260740       434576          2013-08-22                     0      J      10
260741       434577          2013-02-05                     0      F      23
260742       434578          2013-09-08                     0      B      24
260743       434579          2013-05-02                     0      B      23
260744       434580          2013-10-28                     0      F      23
260745       434581          2015-03-05                     0      K      21
260746       434582          2014-08-01                     0      F       7
260747       434583          2014-11-12                     1      F       7
260748       434584          2013-05-16                     0      J      23
260749       434585          2014-12-07                     0      J      26
260750       434586          2014-02-18                     0      F      11
260751       434587          2014-04-08                     0      F       7
260752       434588          2013-03-19                     0      F      15

        Field8  Field9 Field10  Field11 Field12        ...          \
0       0.9403  0.0006     965   1.0200       N        ...
1       1.0006  0.0040     548   1.2433       N        ...
2       1.0006  0.0040     548   1.2433       N        ...
3       0.9769  0.0004   1,165   1.2665       N        ...
4       0.9472  0.0006   1,487   1.3045       N        ...
5       0.9472  0.0006   1,487   1.3045       N        ...
6       0.9258  0.0004   1,165   1.2665       N        ...
7       0.9153  0.0007     935   1.0200       N        ...
8       0.9691  0.0004   1,165   1.2665       N        ...
9       0.9919  0.0038     564   1.1886       N        ...
10      0.9403  0.0006     965   1.0200       N        ...
11      0.9403  0.0006     965   1.0200       N        ...
12      0.9497  0.0004   1,165   1.2665       N        ...
13      0.9403  0.0006     965   1.0200       N        ...
14      0.9893  0.0040     548   1.2433       N        ...
15      0.8793  0.0004   1,113   1.2665       N        ...
16      0.9153  0.0007     935   1.0200       N        ...
17      0.9919  0.0038     564   1.1886       N        ...
18      0.9153  0.0007     935   1.0200       N        ...
19      0.9485  0.0006   1,480   1.3045       N        ...
20      0.8922  0.0004   1,113   1.2665       N        ...
21      0.8793  0.0004   1,113   1.2665       N        ...
22      1.0006  0.0040     548   1.2433       N        ...
23      1.0101  0.0040     548   1.2694       N        ...
24      0.9403  0.0006     965   1.0200       N        ...
25      1.0101  0.0040     548   1.2694       N        ...
26      0.9403  0.0006     965   1.0200       N        ...
27      0.8930  0.0006   1,487   1.3045       Y        ...
28      0.9691  0.0004   1,165   1.2665       N        ...
29      0.9219  0.0006     965   1.0000       N        ...
...        ...     ...     ...      ...     ...        ...
260723  0.8870  0.0004   1,113   1.2665       Y        ...
260724  0.8870  0.0004   1,113   1.2665       Y        ...
260725  0.9403  0.0007     935   1.0200       N        ...
260726  0.8928  0.0004   1,113   1.2665       N        ...
260727  0.9153  0.0007     935   1.0200       N        ...
260728  0.9403  0.0006     965   1.0200       N        ...
260729  0.9108  0.0006   1,487   1.3045       Y        ...
260730  0.9919  0.0038     564   1.1886       N        ...
260731  0.8928  0.0004   1,113   1.2665       N        ...
260732  1.0101  0.0040     548   1.2694       N        ...
260733  0.9403  0.0007     935   1.0200       N        ...
260734  0.8922  0.0004   1,113   1.2665       N        ...
260735  0.9313  0.0038     564   1.1161       N        ...
260736  0.9403  0.0006     965   1.0200       N        ...
260737  0.9392  0.0006   1,487   1.3045       N        ...
260738  0.9392  0.0006   1,487   1.3045       N        ...
260739  0.9403  0.0007     935   1.0200       N        ...
260740  0.9691  0.0004   1,165   1.2665       N        ...
260741  0.9023  0.0038     564   1.0670       N        ...
260742  0.9403  0.0006     965   1.0200       N        ...
260743  0.9403  0.0006     965   1.0200       N        ...
260744  0.9919  0.0038     564   1.1886       N        ...
260745  0.8870  0.0004   1,113   1.2665       Y        ...
260746  1.0006  0.0040     548   1.2433       N        ...
260747  1.0006  0.0040     548   1.2433       N        ...
260748  0.9691  0.0004   1,165   1.2665       N        ...
260749  0.8870  0.0004   1,113   1.2665       N        ...
260750  0.9685  0.0040     548   1.1886       N        ...
260751  1.0006  0.0040     548   1.2433       N        ...
260752  0.8945  0.0038     564   1.0670       N        ...

        GeographicField59A  GeographicField59B  GeographicField60A  \
0                        9                   9                  -1
1                       10                  10                  -1
2                       15                  18                  -1
3                        6                   5                  -1
4                       18                  22                  -1
5                       10                  11                  -1
6                       18                  22                  -1
7                        6                   5                  -1
8                        2                   1                  -1
9                       10                  11                  -1
10                      10                  11                  -1
11                       9                   9                  -1
12                      16                  20                  -1
13                      13                  16                  -1
14                      15                  18                  -1
15                       8                   8                  -1
16                      25                  25                  -1
17                       7                   6                  -1
18                      20                  24                  -1
19                      13                  16                  -1
20                      19                  23                  -1
21                      11                  13                  -1
22                      14                  16                  -1
23                      11                  12                  -1
24                      10                  10                  -1
25                      13                  16                  25
26                      14                  17                  -1
27                      11                  12                  -1
28                      10                  10                  -1
29                       6                   5                  -1
...                    ...                 ...                 ...
260723                   9                   9                  -1
260724                  12                  14                  -1
260725                  10                  11                  -1
260726                   9                   8                  -1
260727                   9                  10                  -1
260728                  15                  19                  -1
260729                   6                   5                  -1
260730                   9                   9                  -1
260731                   8                   7                  -1
260732                  12                  14                  -1
260733                  14                  17                  -1
260734                   2                   1                  -1
260735                   8                   8                  -1
260736                   1                   1                  -1
260737                  18                  22                  -1
260738                  12                  14                  -1
260739                  16                  20                  25
260740                  25                  25                  -1
260741                  14                  16                  -1
260742                  18                  22                  -1
260743                   6                   5                  -1
260744                  16                  20                  -1
260745                  18                  22                  -1
260746                  14                  18                  -1
260747                  11                  13                  -1
260748                   7                   6                  -1
260749                   5                   4                  25
260750                  16                  20                  -1
260751                  10                  11                  -1
260752                  25                  25                  -1

        GeographicField60B  GeographicField61A  GeographicField61B  \
0                        8                  -1                  18
1                       11                  -1                  17
2                       21                  -1                  11
3                       10                  -1                   9
4                       10                  -1                  11
5                       23                  -1                  25
6                       19                  -1                  13
7                        3                  -1                  12
8                        3                  -1                   2
9                        9                  -1                  22
10                      14                  -1                  14
11                      14                  -1                   7
12                      24                  -1                   8
13                      17                  25                  25
14                      23                  -1                   2
15                       7                  -1                  21
16                      18                  -1                  18
17                      16                  -1                  13
18                      22                  -1                   6
19                       1                  -1                   8
20                      22                  -1                  11
21                       2                  -1                  20
22                      19                  -1                   5
23                      12                  25                  25
24                      14                  -1                  19
25                      25                  -1                   4
26                      20                  -1                   2
27                       2                  -1                  23
28                       1                  -1                  14
29                       6                  -1                  23
...                    ...                 ...                 ...
260723                  25                  -1                   3
260724                   1                  -1                  16
260725                  11                  -1                  13
260726                   5                  -1                   5
260727                  12                  -1                  19
260728                  19                  -1                   4
260729                  19                  -1                  15
260730                   7                  25                  25
260731                  11                  -1                  16
260732                  13                  -1                  21
260733                  20                  -1                  12
260734                   6                  25                  25
260735                  18                  -1                  20
260736                   1                  25                  25
260737                   7                  -1                  21
260738                   8                  -1                  21
260739                  25                  -1                   6
260740                  24                  -1                   9
260741                  20                  -1                  23
260742                  18                  -1                   7
260743                   6                  -1                  20
260744                   4                  -1                  18
260745                  17                  -1                  10
260746                   6                  -1                  17
260747                   5                  -1                  24
260748                  22                  -1                  20
260749                  25                  -1                   2
260750                  10                  -1                   9
260751                  23                  -1                  10
260752                  14                  -1                   4

        GeographicField62A  GeographicField62B  GeographicField63  \
0                       -1                  10                  N
1                       -1                  20                  N
2                       -1                   8                  N
3                       -1                  21                  N
4                       -1                  12                  N
5                       -1                  14                  N
6                       -1                   8                  N
7                       -1                  13                  N
8                       -1                  13                  N
9                       -1                  18                  N
10                      -1                   8                  N
11                      -1                   8                  N
12                      -1                  14                  N
13                      -1                  13                  N
14                      -1                   8                  N
15                      -1                  12                  N
16                      -1                  19                  N
17                      -1                   8                  N
18                      -1                   9                  N
19                      -1                   8                  N
20                      -1                   8                  N
21                      -1                  20                  N
22                      -1                  20                  N
23                      -1                  12                  N
24                      -1                  17                  N
25                      25                  25                  N
26                      -1                  17                  N
27                      -1                  22                  N
28                      25                  25                  N
29                      -1                   8                  N
...                    ...                 ...                ...
260723                  -1                  13                  N
260724                  -1                   8                  N
260725                  -1                   8                  N
260726                  -1                  18                  N
260727                  -1                   8                  N
260728                  -1                   8                  N
260729                  -1                  22                  N
260730                  -1                   8                  N
260731                  -1                  10                  N
260732                  -1                  22                  N
260733                  -1                   8                  N
260734                  -1                  18                  N
260735                  -1                  16                  N
260736                  -1                  23                  N
260737                  -1                  25                  N
260738                  -1                  10                  N

In [44]:
print(df.isnull().sum())

QuoteConversion_Flag    0
Field6                  0
Field7                  0
Field8                  0
Field9                  0
Field10                 0
Field11                 0
Field12                 0
CoverageField1A         0
CoverageField1B         0
CoverageField2A         0
CoverageField2B         0
CoverageField3A         0
CoverageField3B         0
CoverageField4A         0
CoverageField4B         0
CoverageField5A         0
CoverageField5B         0
CoverageField6A         0
CoverageField6B         0
CoverageField8          0
CoverageField9          0
CoverageField11A        0
CoverageField11B        0
SalesField1A            0
SalesField1B            0
SalesField2A            0
SalesField2B            0
SalesField3             0
SalesField4             0
                       ..
GeographicField51A      0
GeographicField51B      0
GeographicField52A      0
GeographicField52B      0
GeographicField53A      0
GeographicField53B      0
GeographicField54A      0
GeographicField54B      0
GeographicField55A      0
GeographicField55B      0
GeographicField56A      0
GeographicField56B      0
GeographicField57A      0
GeographicField57B      0
GeographicField58A      0
GeographicField58B      0
GeographicField59A      0
GeographicField59B      0
GeographicField60A      0
GeographicField60B      0
GeographicField61A      0
GeographicField61B      0
GeographicField62A      0
GeographicField62B      0
GeographicField63       0
GeographicField64       0
weekday                 0
weekyear                0
Year                    0
Month                   0
Length: 301, dtype: int64

In [18]:
import pandas as pd
from IPython.core.display import HTML

#df=pd.read_pickle('Data1')
#display(HTML(df.to_html()))

In [15]:
df = df.set_index('Original_Quote_Date')

df.index = df.index.to_datetime()

AttributeError: 'Index' object has no attribute 'to_datetime'

In [25]:
df['Date']=pd.to_datetime(pd.Series(df['Original_Quote_Date']))

In [26]:
df = df.drop(["Original_Quote_Date","QuoteNumber"],axis=1)

In [27]:
df['weekday'] = df['Date'].dt.dayofweek
df['weekyear'] = df['Date'].dt.weekofyear
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

In [28]:
df=df.drop(["Date"], axis=1)

In [29]:
df.head()

,QuoteConversion_Flag,Field6,Field7,Field8,Field9,Field10,Field11,Field12,CoverageField1A,CoverageField1B,...,GeographicField61A,GeographicField61B,GeographicField62A,GeographicField62B,GeographicField63,GeographicField64,weekday,weekyear,Year,Month
0,0,B,23,0.9403,0.0006,965,1.0200,N,17,23,...,-1,18,-1,10,N,CA,4,33,2013,8
1,0,F,7,1.0006,0.0040,548,1.2433,N,6,8,...,-1,17,-1,20,N,NJ,1,17,2014,4
2,0,F,7,1.0006,0.0040,548,1.2433,N,7,12,...,-1,11,-1,8,N,NJ,0,35,2014,8
3,0,J,10,0.9769,0.0004,"1,165",1.2665,N,3,2,...,-1,9,-1,21,N,TX,0,16,2013,4
4,0,E,23,0.9472,0.0006,"1,487",1.3045,N,8,13,...,-1,11,-1,12,N,IL,5,4,2014,1

In [40]:
import sklearn
from sklearn import preprocessing

In [30]:
print(df)

        QuoteConversion_Flag Field6  Field7  Field8  Field9 Field10  Field11  \
0                          0      B      23  0.9403  0.0006     965   1.0200
1                          0      F       7  1.0006  0.0040     548   1.2433
2                          0      F       7  1.0006  0.0040     548   1.2433
3                          0      J      10  0.9769  0.0004   1,165   1.2665
4                          0      E      23  0.9472  0.0006   1,487   1.3045
5                          0      E      14  0.9472  0.0006   1,487   1.3045
6                          0      J      23  0.9258  0.0004   1,165   1.2665
7                          0      B      25  0.9153  0.0007     935   1.0200
8                          0      J      10  0.9691  0.0004   1,165   1.2665
9                          0      F      11  0.9919  0.0038     564   1.1886
10                         0      B      23  0.9403  0.0006     965   1.0200
11                         0      B      23  0.9403  0.0006     965   1.0200
12                         1      J      20  0.9497  0.0004   1,165   1.2665
13                         1      B      24  0.9403  0.0006     965   1.0200
14                         0      F      22  0.9893  0.0040     548   1.2433
15                         0      J      26  0.8793  0.0004   1,113   1.2665
16                         0      B      25  0.9153  0.0007     935   1.0200
17                         1      F      11  0.9919  0.0038     564   1.1886
18                         0      B      25  0.9153  0.0007     935   1.0200
19                         0      E      23  0.9485  0.0006   1,480   1.3045
20                         0      J      26  0.8922  0.0004   1,113   1.2665
21                         0      J      23  0.8793  0.0004   1,113   1.2665
22                         0      F       7  1.0006  0.0040     548   1.2433
23                         0      F      22  1.0101  0.0040     548   1.2694
24                         0      B      19  0.9403  0.0006     965   1.0200
25                         1      F      22  1.0101  0.0040     548   1.2694
26                         0      B      24  0.9403  0.0006     965   1.0200
27                         0      C      17  0.8930  0.0006   1,487   1.3045
28                         0      J      23  0.9691  0.0004   1,165   1.2665
29                         0      B       6  0.9219  0.0006     965   1.0000
...                      ...    ...     ...     ...     ...     ...      ...
260723                     0      K      21  0.8870  0.0004   1,113   1.2665
260724                     0      K      21  0.8870  0.0004   1,113   1.2665
260725                     0      B      23  0.9403  0.0007     935   1.0200
260726                     0      J      23  0.8928  0.0004   1,113   1.2665
260727                     0      B      23  0.9153  0.0007     935   1.0200
260728                     0      B      23  0.9403  0.0006     965   1.0200
260729                     0      C      17  0.9108  0.0006   1,487   1.3045
260730                     0      F      11  0.9919  0.0038     564   1.1886
260731                     0      J      23  0.8928  0.0004   1,113   1.2665
260732                     0      F      23  1.0101  0.0040     548   1.2694
260733                     1      B      25  0.9403  0.0007     935   1.0200
260734                     0      J      23  0.8922  0.0004   1,113   1.2665
260735                     0      F      23  0.9313  0.0038     564   1.1161
260736                     0      B      24  0.9403  0.0006     965   1.0200
260737                     0      E      23  0.9392  0.0006   1,487   1.3045
260738                     0      E      23  0.9392  0.0006   1,487   1.3045
260739                     0      B      25  0.9403  0.0007     935   1.0200
260740                     0      J      10  0.9691  0.0004   1,165   1.2665
260741                     0      F      23  0.9023  0.0038     564   1.0670
260742                     0      B      24  0.9403  0.0006     965   1.0200
260743                     0      B      23  0.9403  0.0006     965   1.0200
260744                     0      F      23  0.9919  0.0038     564   1.1886
260745                     0      K      21  0.8870  0.0004   1,113   1.2665
260746                     0      F       7  1.0006  0.0040     548   1.2433
260747                     1      F       7  1.0006  0.0040     548   1.2433
260748                     0      J      23  0.9691  0.0004   1,165   1.2665
260749                     0      J      26  0.8870  0.0004   1,113   1.2665
260750                     0      F      11  0.9685  0.0040     548   1.1886
260751                     0      F       7  1.0006  0.0040     548   1.2433
260752                     0      F      15  0.8945  0.0038     564   1.0670

       Field12  CoverageField1A  CoverageField1B  ...    GeographicField61A  \
0            N               17               23  ...                    -1
1            N                6                8  ...                    -1
2            N                7               12  ...                    -1
3            N                3                2  ...                    -1
4            N                8               13  ...                    -1
5            N               13               20  ...                    -1
6            N               16               23  ...                    -1
7            N                5                8  ...                    -1
8            N                5                8  ...                    -1
9            N               11               19  ...                    -1
10           N                4                4  ...                    -1
11           N                8               14  ...                    -1
12           N               18               23  ...                    -1
13           N                5                6  ...                    25
14           N               10               17  ...                    -1
15           N                8               14  ...                    -1
16           N                6                8  ...                    -1
17           N                4                4  ...                    -1
18           N               12               20  ...                    -1
19           N                5                7  ...                    -1
20           N               14               22  ...                    -1
21           N                1                1  ...                    -1
22           N               12               19  ...                    -1
23           N                9               15  ...                    25
24           N                5                7  ...                    -1
25           N               13               20  ...                    -1
26           N               23               25  ...                    -1
27           Y                5                6  ...                    -1
28           N                7               11  ...                    -1
29           N                6                9  ...                    -1
...        ...              ...              ...  ...                   ...
260723       Y               15               22  ...                    -1
260724       Y                4                5  ...                    -1
260725       N               11               18  ...                    -1
260726       N               14               21  ...                    -1
260727       N                8               13  ...                    -1
260728       N                6                9  ...                    -1
260729       Y                5                7  ...                    -1
260730       N                2                2  ...                    25
260731       N                3                2  ...                    -1
260732       N               18               23  ...                    -1
260733       N               12               19  ...                    -1
260734       N               11               18  ...                    25
260735       N                2                1  ...                    -1
260736       N                2                2  ...                    25
260737       N                9               15  ...                    -1
260738       N                7               11  ...                    -1
260739       N                7               12  ...                    -1
260740       N                7               11  ...                    -1
260741       N                5                7  ...                    -1
260742       N                7               12  ...                    -1
260743       N                7               11  ...                    -1
260744       N                7               11  ...                    -1
260745       Y               13               20  ...                    -1
260746       N                8               14  ...                    -1
260747       N                4                5  ...                    -1
260748       N                9               15  ...                    -1
260749       N               15               22  ...                    -1
260750       N                6                9  ...                    -1
260751       N               16               23  ...                    -1
260752       N                2                2  ...                    -1

        GeographicField61B  GeographicField62A  GeographicField62B  \
0                       18                  -1                  10
1                       17                  -1                  20
2                       11                  -1                   8
3                        9                  -1                  21
4                       11                  -1                  12
5                       25                  -1                  14
6                       13                  -1                   8
7                       12                  -1                  13
8                        2                  -1                  13
9                       22                  -1                  18
10                      14                  -1                   8
11                       7                  -1                   8
12                       8                  -1                  14
13                      25                  -1                  13
14                       2                  -1                   8
15                      21                  -1                  12
16                      18                  -1                  19
17                      13                  -1                   8
18                       6                  -1                   9
19                       8                  -1                   8
20                      11                  -1                   8
21                      20                  -1                  20
22                       5                  -1                  20
23                      25                  -1                  12
24                      19                  -1                  17
25                       4                  25                  25
26                       2                  -1                  17
27                      23                  -1                  22
28                      14                  25                  25
29                      23                  -1                   8
...                    ...                 ...                 ...
260723                   3                  -1                  13
260724                  16                  -1                   8
260725                  13                  -1                   8
260726                   5                  -1                  18
260727                  19                  -1                   8
260728                   4                  -1                   8
260729                  15                  -1                  22
260730                  25                  -1                   8
260731                  16                  -1                  10
260732                  21                  -1                  22
260733                  12                  -1                   8
260734                  25                  -1                  18
260735                  20                  -1                  16
260736                  25                  -1                  23
260737                  21                  -1                  25
260738                  21                  -1                  10
260739                   6                  -1                   8
260740                   9                  25                  25
260741                  23                  -1                   8
260742                   7                  -1                  13
260743                  20                  -1                  17
260744                  18                  -1                  19
260745                  10                  -1                  16
260746                  17                  -1                   8
260747                  24                  -1                   8
260748                  20                  -1                   8
260749                   2                  -1                  20
260750                   9                  -1                   8
260751                  10                  -1                  16
260752                   4                  -1                   8

        GeographicField63  GeographicField64  weekday  weekyear  Year  Month
0                       N                 CA        4        33  2013      8
1                       N                 NJ        1        17  2014      4
2                       N                 NJ        0        35  2014      8
3                       N                 TX        0        16  2013      4
4                       N                 IL        5         4  2014      1
5                       N                 IL        5         3  2014      1
6                       N                 TX        4        44  2013     11
7                       N                 CA        2        20  2014      5
8                       N                 TX        2        25  2013      6
9                       N                 NJ        1        25  2013      6
10                      N                 CA        1        39  2013      9
11                      N                 CA        1        24  2013      6
12                      N                 TX        1        43  2013     10
13                      N                 CA        1        34  2013      8
14                      N                 NJ        1         9  2015      2
15                      N                 TX        0        44  2014     10
16                      N                 CA        4         6  2015      2
17                      N                 NJ        2        40  2013     10
18                      N                 CA        0        38  2014      9
19                      N                 IL        1        25  2013      6
20                      N                 TX        1        12  2014      3
21                      N                 TX        2        42  2014     10
22                      N                 NJ        3        14  2014      4
23                      N                 NJ        1        14  2015      3
24                      N                 CA        3        22  2013      5
25                      N                 NJ        0        14  2015      3
26                      N                 CA        1        38  2013      9
27                      N                 IL        5        10  2015      3
28                      N                 TX        3        23  2013      6
29                      N                 CA        1         4  2013      1
...                   ...                ...      ...       ...   ...    ...
260723                  N                 TX        2         2  2015      1
260724                  N                 TX        5        15  2015      4
260725                  N                 CA        0         4  2014      1
260726                  N                 TX        2        20  2014      5
260727                  N                 CA        1        14  2015      3
260728                  N                 CA        2        40  2013     10
260729                  N                 IL        2         8  2015      2
260730                  N                 NJ        5        45  2013     11
260731                  N                 TX        6        29  2014      7
260732                  N                 NJ        2        14  2015      4
260733                  N                 CA        1         6  2014      2
260734                  N                 TX        1         4  2014      1
260735                  N                 NJ        6        16  2013      4
260736                  N                 CA        0        27  2013      7
260737                  N                 IL        0        11  2014      3
260738                  N                 IL        4        15  2014      4
260739                  N                 CA        4         4  2014      1
260740                  N                 TX        3        34  2013      8
260741                  N                 NJ        1         6  2013      2
260742                  N                 CA        6        36  2013      9
260743                  N                 CA        3        18  2013      5
260744                  N                 NJ        0        44  2013     10
260745                  N                 TX        3        10  2015      3
260746                  N                 NJ        4        31  2014      8
260747                  N                 NJ        2        46  2014     11
260748                  N                 TX        3        20  2013      5
260749                  N                 TX        6        49  2014     12
260750                  N                 NJ        1         8  2014      2
260751                  N                 NJ        1        15  2014      4
260752                  N                 NJ        1        12  2013      3

[260753 rows x 301 columns]

In [42]:
a=[]
for columns in df.columns:
    if df[columns].dtype=="object":
        #a.append(columns)
        lbl=preprocessing.LabelEncoder()
        lbl.fit(list(df[columns].values))
        df[columns]=lbl.transform(list(df[columns].values))
#print(a)

In [68]:
df=df.fillna(-99)

In [70]:
df.isnull().sum().sum()

0

In [61]:
#df.columns[df.isna().any()].tolist()
#df['PersonalField84']

['PersonalField84', 'PropertyField29']

In [71]:
df.head()

,QuoteConversion_Flag,Field6,Field7,Field8,Field9,Field10,Field11,Field12,CoverageField1A,CoverageField1B,...,GeographicField61A,GeographicField61B,GeographicField62A,GeographicField62B,GeographicField63,GeographicField64,weekday,weekyear,Year,Month
0,0,1,23,0.9403,0.0006,7,1.0200,0,17,23,...,-1,18,-1,10,1,0,4,33,2013,8
1,0,5,7,1.0006,0.0040,4,1.2433,0,6,8,...,-1,17,-1,20,1,2,1,17,2014,4
2,0,5,7,1.0006,0.0040,4,1.2433,0,7,12,...,-1,11,-1,8,1,2,0,35,2014,8
3,0,6,10,0.9769,0.0004,1,1.2665,0,3,2,...,-1,9,-1,21,1,3,0,16,2013,4
4,0,4,23,0.9472,0.0006,3,1.3045,0,8,13,...,-1,11,-1,12,1,1,5,4,2014,1

In [74]:
X=df.copy()
X=X.drop(['QuoteConversion_Flag'],axis=1)

In [75]:
y=df['QuoteConversion_Flag']

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                                    test_size=0.4,
                                                    random_state=0)

In [124]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
kfold=StratifiedKFold(n_splits=2, random_state=7)

In [125]:
result=cross_val_score(clf,X_train,y_train,cv=kfold)

C:\Users\sam\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\sam\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [127]:
result.mean()

0.9242702200948082

In [128]:
result.std()

0.00020405283584057354

In [111]:
import xgboost as xgb

In [112]:
#clf=xgb.XGBClassifier(n_estimators=100, learning_rate=0.01,nthread=-1,max_depth=12,subsample=0.6,colsample_bytree=0.6,
                      #silent=False,Verbose=10)

In [113]:
#clf=xgb.XGBClassifier(objective = 'binary:logistic', eta=0.1,n_estimators=100,silent=False,verbose=10)
#clf=xgb.XGBClassifier(objective = 'binary:logistic', eta=0.1,n_estimators=100,max_depth=10,silent=False,verbose=10)
#clf=xgb.XGBClassifier(objective = 'binary:logistic', eta=0.1,n_estimators=100,max_depth=10,alpha=1,silent=False,verbose=10)
clf=xgb.XGBClassifier(objective = 'binary:logistic', eta=0.1,n_estimators=100,max_depth=7,colsample_bytree=0.8,
                      alpha=1,gamma=0.1,subsample=0.8,silent=False,verbose=10)

In [114]:
clf.fit(X_train, y_train)

XGBClassifier(alpha=1, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.8, eta=0.1, gamma=0.1, learning_rate=0.1,
       max_delta_step=0, max_depth=7, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=False,
       subsample=0.8, verbose=10)

In [115]:
clf_xgb=clf.predict(X_test)

C:\Users\sam\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [116]:
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, recall_score, precision_score, accuracy_score
from sklearn.cross_validation import cross_val_score

In [117]:
print(confusion_matrix(y_test, clf_xgb))
print(classification_report(y_test,clf_xgb))

[[83326  1428]
 [ 6232 13316]]
             precision    recall  f1-score   support

          0       0.93      0.98      0.96     84754
          1       0.90      0.68      0.78     19548

avg / total       0.93      0.93      0.92    104302

# Precison - 0.95; recall - 0.68; Fl score - 0.74
#with params: eta =0.1, n_estimators=100,verbose=10

# Precison - 0.95; recall - 0.68; Fl score - 0.78
#with params: eta =0.1, n_estimators=100,maxdepth=10,verbose=10

# Precison - 0.95; recall - 0.68; Fl score - 0.78
#with params: eta =0.1, n_estimators=100,alpha=1,maxdepth=10,verbose=10